---
title: LEGO® remote controlled car
hero_image: images/banner.png
description: Make a remote controlled car with LEGO® and the Build HAT
version: 4
listed: true
copyedit: true
last_tested: '2020-02-26'
steps:
- title: Introduction
- title: Set up the LEGO® Spike™ motors
- title: Set up and test the Bluetooth control
  completion:
  - engaged
- title: Control your motors with Blue Dot
- title: Assemble your robot
- title: Add LEDs
  completion:
  - internal
- title: What next?
