title: Remote control LEGO buggy
hero_image: images/banner.png
description: bt-robot-car description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-26"
steps:
  - title: Introduction
  - title: Setting up the LEGO® Technic™ motors
  - title: Set up and test the Bluetooth control
  - title: Control your motors with Blue Dot
  - title: Assembling your robot
  - title: Adding LEDs
  - title: What next?
