title: bt-robot-car
hero_image: images/banner.jpg
description: bt-robot-car description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-26"
steps:
  - title: Introduction
  - title: Setting up your motors
  - title: Bluetooth control
  - title: Assembling your robot
  - title: Adding LEDs
