title: LEGO® remote controlled car
hero_image: images/banner.png
description: Make a remote controlled car with LEGO® and the Build HAT
version: 4
listed: false
copyedit: false
last_tested: "2020-02-26"
steps:
  - title: Introduction
  - title: Setting up the LEGO® Spike™ motors
  - title: Set up and test the Bluetooth control
  - title: Control your motors with Blue Dot
  - title: Assembling your robot
  - title: Adding LEDs
  - title: What next?
