---
title: LEGO® ラジコンカー
hero_image: images/banner.png
description: LEGO® と BuildHAT でリモコンカーを作る
version: 4
listed: true
copyedit: true
last_tested: "2020-02-26"
steps:
  - 
    title: はじめに
  - 
    title: LEGO® Spike™ モーターをセットアップする
  - 
    title: Bluetooth のセットアップとテスト
  - 
    title: Blue Dotでモーターを制御する
  - 
    title: ロボットを組み立てる
  - 
    title: LEDを追加する
  - 
    title: What next?
