---
title: Carro LEGO® a control remoto
hero_image: images/banner.png
description: Crea un carro a control remoto con LEGO® y Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-02-26"
steps:
  - 
    title: Introducción
  - 
    title: Configuración de los motores LEGO® Spike ™
  - 
    title: Configura y pruebe el control de Bluetooth
  - 
    title: Controla tus motores con Blue Dot
  - 
    title: Armando tu robot
  - 
    title: Añadiendo LEDs
  - 
    title: '¿Qué viene a continuación?'
