---
title: Ferngesteuertes LEGO® Auto
hero_image: images/banner.png
description: Baue ein ferngesteuertes Auto mit LEGO® und dem Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-02-26"
steps:
  - title: Einleitung
  - title: Einrichten der LEGO® Spike™ Motoren
  - title: Bluetooth-Steuerung einrichten und testen
  - title: Steuern der Motoren mit Blue Dot
  - title: Zusammenbau des Roboters
  - title: LEDs hinzufügen
  - title: Wie geht es weiter?
