---
title: Ferngesteuertes LEGO® Auto
hero_image: images/banner.png
description: Baue ein ferngesteuertes Auto mit LEGO® und dem Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-02-26"
steps:
  - 
    title: Einleitung
  - 
    title: Set up the LEGO® Spike™ motors
  - 
    title: Bluetooth-Steuerung einrichten und testen
  - 
    title: Steuern der Motoren mit Blue Dot
  - 
    title: Assemble your robot
  - 
    title: Add LEDs
  - 
    title: Wie geht es weiter?
