---
title: LEGO® 원격조종 자동차
hero_image: images/banner.png
description: LEGO®와 Build HAT로 원격조종 자동차를 만드세요
version: 4
listed: true
copyedit: true
last_tested: '2020-02-26'
steps:
- title: 들어가며
- title: LEGO® Spike™ 모터설정
- title: Bluetooth 설정 및 테스트
  completion:
  - engaged
- title: Blue Dot으로 모터 제어하기
- title: 로봇 조립
- title: LED 추가하기
  completion:
  - internal